### ISSUE TITLE
How to use Multinomial family

### ISSUE THREAD

**Issue by youngjaewoo** [JuliaStats/GLMNet.jl#21]
Hello, how do you use Multinomial() or other methods in the family option? I tried

`glmnet(X,Y, family::Multinomial())` and `glmnet(X,Y, family=:Multinomial())` where X and Y are both 2-D arrays.

Probably an easy question, but I just couldn't figure out how to use it. Thanks for your help.

**Comment by linxihui** [comment]
@youngjaewoo  If you read the the README file closely, you'll notice that  "only Normal() (least squares, default), Binomial() (logistic), and Poisson() are supported". 

Indeed, the support of Multinomial and other models is available in my PR here https://github.com/simonster/GLMNet.jl/pull/10. But not merged yet. It currently has conflicts since the merge of sparse matrix support.  You can use an older version, or use my branch directly.

**Comment by youngjaewoo** [comment]
@linxihui Thanks. I really want to try out your branch but I'm not good at github yet. Can you help me with what could be wrong with the below usage?

```
git remote add linxihui https://github.com/linxihui/GLMNet.jl.git

git remote update
Fetching linxihui
remote: Counting objects: 431, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 431 (delta 0), reused 2 (delta 0), pack-reused 429
Receiving objects: 100% (431/431), 229.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (219/219), done.
From https://github.com/linxihui/GLMNet.jl
 * [new branch]      master     -> linxihui/master
 * [new tag]         v0.0.3     -> v0.0.3
 * [new tag]         v0.0.4     -> v0.0.4

git checkout linxihui/GLMNet.jl
error: pathspec 'linxihui/GLMNet.jl' did not match any file(s) known to git.
```

Or, is there a easier way to do this? It's probably something easy, but I can't figure it out even after spending hours googling.. Thanks much

**Comment by linxihui** [comment]
@youngjaewoo  I don't know how to remote add.  But you can use `git clone`, or you can directly install in julia as following:
```julia
Pkg.clone("git://github.com/linxihui/GLMNet.jl")
Pkg.build("GLMNet")
```

**Comment by JackDunnNZ** [comment]
Added in #50
